name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest  # The job runs on a GitHub-hosted runner

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Deploy to Raspberry Pi
      uses: appleboy/ssh-action@master
      with:
        host: "192.168.1.211"
        username: pi 
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/html
    
          rm -rf *
          cp -R $GITHUB_WORKSPACE/piweb/* .

